name: math
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - scipy
  - ipython
  - jupyter
  - mkl
  - sympy
  - pip
  - latex
  - dvipng
  - pip:
    # - cualquier-paquete-extra