name: edp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - scipy
  - mkl
  - sympy
  - matplotlib
  - fenics-dolfinx   # 
  - gmsh             # Alternativa a mshr
  - pyvista          # Para visualización en Windows